import { FilterParameter } from './filterTypes';

// 滤镜参数配置
export const FILTER_PARAMETERS: { [key: string]: FilterParameter[] } = {
  oil_painting: [
    {
      name: 'radius',
      label: '笔刷半径',
      type: 'slider',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: 5,
    },
    {
      name: 'intensity',
      label: '强度',
      type: 'slider',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: 10,
    },
  ],
  watercolor: [
    {
      name: 'sigma_s',
      label: '平滑度',
      type: 'slider',
      min: 10,
      max: 120,
      step: 10,
      defaultValue: 60,
    },
    {
      name: 'sigma_r',
      label: '色彩保留',
      type: 'slider',
      min: 0.1,
      max: 1,
      step: 0.1,
      defaultValue: 0.6,
    },
    {
      name: 'texture_strength',
      label: '纹理强度',
      type: 'slider',
      min: 0,
      max: 0.5,
      step: 0.05,
      defaultValue: 0.1,
    },
  ],
  dry_brush: [
    {
      name: 'brush_size',
      label: '笔刷大小',
      type: 'slider',
      min: 3,
      max: 15,
      step: 2,
      defaultValue: 5,
    },
    {
      name: 'detail_level',
      label: '细节级别',
      type: 'slider',
      min: 5,
      max: 50,
      step: 5,
      defaultValue: 25,
    },
    {
      name: 'texture_strength',
      label: '纹理强度',
      type: 'slider',
      min: 0.05,
      max: 0.5,
      step: 0.05,
      defaultValue: 0.15,
    },
  ],
  pencil_sketch: [
    {
      name: 'sigma_s',
      label: '平滑度',
      type: 'slider',
      min: 10,
      max: 150,
      step: 10,
      defaultValue: 60,
    },
    {
      name: 'sigma_r',
      label: '细节保留',
      type: 'slider',
      min: 0.01,
      max: 0.2,
      step: 0.01,
      defaultValue: 0.07,
    },
    {
      name: 'shade_factor',
      label: '阴影因子',
      type: 'slider',
      min: 0,
      max: 0.3,
      step: 0.01,
      defaultValue: 0.1,
    },
  ],
  fresco: [
    {
      name: 'roughness',
      label: '粗糙度',
      type: 'slider',
      min: 0.1,
      max: 1.5,
      step: 0.1,
      defaultValue: 0.8,
    },
    {
      name: 'cracks',
      label: '裂痕强度',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.1,
      defaultValue: 0.6,
    },
    {
      name: 'color_decay',
      label: '颜色褪色',
      type: 'slider',
      min: 0,
      max: 0.8,
      step: 0.1,
      defaultValue: 0.4,
    },
  ],
  colored_pencil: [
    {
      name: 'line_size',
      label: '线条大小',
      type: 'slider',
      min: 3,
      max: 15,
      step: 1,
      defaultValue: 7,
    },
    {
      name: 'blur_value',
      label: '模糊值',
      type: 'slider',
      min: 3,
      max: 15,
      step: 1,
      defaultValue: 7,
    },
    {
      name: 'edge_threshold',
      label: '边缘阈值',
      type: 'slider',
      min: 20,
      max: 100,
      step: 10,
      defaultValue: 50,
    },
  ],
}; 