import { ApiEndpoint } from '../../types/api';

export const overlayEndpoint: ApiEndpoint = {
  method: 'POST',
  path: '/api/v1/overlay',
  urlPath: '/api/v1/overlay-by-url',
  description: '为图片添加各种叠加效果。',
  category: '叠加效果',
  requestType: {
    file: 'multipart/form-data',
    url: 'application/json'
  },
  responseType: 'image/jpeg',
  parameters: [
    {
      name: 'overlay_type',
      type: 'select',
      description: '叠加类型',
      required: true,
      defaultValue: 'gradient',
      options: ['gradient', 'vignette', 'pattern'],
    },
    {
      name: 'gradient_type',
      type: 'select',
      description: '渐变类型',
      required: false,
      defaultValue: 'linear',
      options: ['linear', 'radial'],
    },
    {
      name: 'gradient_direction',
      type: 'select',
      description: '线性渐变方向',
      required: false,
      defaultValue: 'to_bottom',
      options: ['to_bottom', 'to_top', 'to_right', 'to_left', 'to_bottom_right', 'to_bottom_left'],
    },
    {
      name: 'start_color',
      type: 'string',
      description: '渐变起始颜色（十六进制）',
      required: false,
      defaultValue: '#000000',
    },
    {
      name: 'end_color',
      type: 'string',
      description: '渐变结束颜色（十六进制）',
      required: false,
      defaultValue: '#FFFFFF',
    },
    {
      name: 'start_opacity',
      type: 'number',
      description: '渐变起始不透明度',
      required: false,
      defaultValue: 0,
      min: 0,
      max: 1,
    },
    {
      name: 'end_opacity',
      type: 'number',
      description: '渐变结束不透明度',
      required: false,
      defaultValue: 0.8,
      min: 0,
      max: 1,
    },
    {
      name: 'intensity',
      type: 'number',
      description: '暗角强度',
      required: false,
      defaultValue: 0.6,
      min: 0,
      max: 1,
    },
    {
      name: 'radius',
      type: 'number',
      description: '暗角半径',
      required: false,
      defaultValue: 1.0,
      min: 0.1,
      max: 1.5,
    },
    {
      name: 'quality',
      type: 'number',
      description: '输出质量',
      required: false,
      defaultValue: 90,
      min: 10,
      max: 100,
    },
  ],
}; 